name: Count Lines of Code

on: [workflow_dispatch]

jobs:
  loc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Count Lines of Code
        uses: PavanMudigonda/lines-of-code-reporter@v1.6
