name: Count Lines of Code

on: [workflow_dispatch]

jobs:
  loc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Count Lines of Code
        id:  loc
        uses: PavanMudigonda/lines-of-code-reporter@v1.6
        with:
          exclude_dir: "node_modules,.github"       #Optional # Comma Seperated
        
    # Publish Lines of Code Summary  # Optional
      - name: Add Lines of Code Summary
        run:  echo "${{ steps.loc.outputs.lines-of-code-summary }}" >> $GITHUB_STEP_SUMMARY
